import java.util.Scanner;
import java.lang.Integer;
import java.lang.Float;
import java.lang.Math;
import java.text.NumberFormat;
import java.util.Random;

public class Numbers {
    public static void main(String[] args) {
        show("First");
        System.out.print("Type something : ");
        Scanner scanner = new Scanner(System.in);
        try {
            Integer.parseInt(scanner.next());
            System.out.println("It's a integer number!");
        } catch (NumberFormatException e) {
            System.out.println("It's NOT a integer number!");
        }
        getch();

        show("Second");
        Float float1 = new Float(0.005f);
        Float float2 = new Float(float1 + 0.04f);
        System.out.println("Is " + float1 + " equals " + float2 + " ? " +
                (float1.equals(float2) ? "Yes" : "No"));
        getch();

        show("Third");
        System.out.println("Is " + float1 + " equals " + float2 + " accurate to 0.05f ? " +
                (Math.abs(float1 - float2) <= 0.05f ? "Yes" : "No"));
        getch();

        show("Fourth");
        double double1 = 1561.98949812;
        float float3 = 5.50198f;
        System.out.println("Rounding double value " + double1 + " : " + Math.round(double1));
        System.out.println("Rounding float value " + float3 + " : " + Math.round(float3));
        getch();

	show("Fifth");
	double double2 = 1623542.765;
	NumberFormat numberFormat = NumberFormat.getNumberInstance();
	System.out.println("Formatting " + double2 + " using NumberFormat.getNumberInstance : " + numberFormat.format(double2));
	getch();

	 show("Sixth");
        double double3 = 0.75;
        numberFormat = NumberFormat.getPercentInstance();
        System.out.println("Formatting " + double3 + " using NumberFormat.getPercentInstance : " + numberFormat.format(double3));
        getch();

	show("Seventh");
	double double4 = 567123678.99;
	numberFormat = NumberFormat.getCurrencyInstance();
        System.out.println("Formatting " + double4 + " using NumberFormat.getCurrencyInstance : " + numberFormat.format(double4));
        getch();

	show("Eighth");
	int value = 24;
	System.out.println("Integer value " + value + " in binary format : " + Integer.toBinaryString(value));
	System.out.println("Integer value " + value + " in octal format : " + Integer.toOctalString(value));
 	System.out.println("Integer value " + value + " in hex format : " + Integer.toHexString(value));
	getch();

	show("Ninth");
	System.out.println("Integer value generated by Random : " + new Random().nextInt());
	System.out.println("Double value generated by Random : " + new Random().nextDouble());
	System.out.println("Value generated by Math.random : " + Math.random());
	getch();

	show("Tenth");
	char tmp = 0x00B0;
	System.out.println("Tangent of angle 45" + tmp +  " : " + Math.tan(Math.toRadians(45)));
	System.out.println("Sine of angle 45" + tmp +  " : " + Math.sin(Math.toRadians(45)));
       	System.out.println("Cosine of angle 45" + tmp +  " : " + Math.cos(Math.toRadians(45)));
	getch();

	show("Eleventh");
	double double5 = 125.5;
	System.out.println("Natural logarithm of value " + double5  + " : " + Math.log(double5));
	getch();
    }

    public static void show(String msg) {
        System.out.println("==========");
        System.out.println(msg + " task");
        System.out.println("==========");
    }

    public static void getch() {
        try {
            System.in.read();
        } catch (Exception e) {
        }
    }
}

